<a href="https://colab.research.google.com/github/teampex/team/blob/main/recomendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

customer_file = list(uploaded.keys())[0]

df_customer = pd.read_csv(customer_file)

print("Customer dataset loaded successfully!")
print("Shape:", df_customer.shape)

Saving customer_data_collection.csv to customer_data_collection (1).csv
Customer dataset loaded successfully!
Shape: (10000, 11)

In [9]:
print("\n--- COLUMNS ---")
print(df_customer.columns.tolist())

print("\n--- DATA TYPES ---")
print(df_customer.dtypes)

print("\n--- MISSING VALUES ---")
print(df_customer.isnull().sum())

print("\n--- FIRST 5 ROWS ---")
display(df_customer.head())

--- COLUMNS ---
['Customer_ID', 'Age', 'Gender', 'Location', 'Browsing_History', 'Purchase_History', 'Customer_Segment', 'Avg_Order_Value', 'Holiday', 'Season', 'Unnamed: 10']

--- DATA TYPES ---
Customer_ID          object
Age                   int64
Gender               object
Location             object
Browsing_History     object
Purchase_History     object
Customer_Segment     object
Avg_Order_Value     float64
Holiday              object
Season               object
Unnamed: 10         float64
dtype: object

--- MISSING VALUES ---
Customer_ID             0
Age                     0
Gender                  0
Location                0
Browsing_History        0
Purchase_History        0
Customer_Segment        0
Avg_Order_Value         0
Holiday                 0
Season                  0
Unnamed: 10         10000
dtype: int64

--- FIRST 5 ROWS ---

,Customer_ID,Age,Gender,Location,Browsing_History,Purchase_History,Customer_Segment,Avg_Order_Value,Holiday,Season,Unnamed: 10
0,C1000,28,Female,Chennai,"['Books', 'Fashion']","['Biography', 'Jeans']",New Visitor,4806.99,No,Winter,NaN
1,C1001,27,Male,Delhi,"['Books', 'Fitness', 'Fashion']","['Biography', 'Resistance Bands', 'T-shirt']",Occasional Shopper,795.03,Yes,Autumn,NaN
2,C1002,34,Other,Chennai,['Electronics'],['Smartphone'],Occasional Shopper,1742.45,Yes,Summer,NaN
3,C1003,23,Male,Bangalore,['Home Decor'],['Wall Art'],Frequent Buyer,2023.16,No,Autumn,NaN
4,C1004,24,Other,Kolkata,"['Fashion', 'Home Decor']","['Shoes', 'Lamp']",Frequent Buyer,794.76,No,Winter,NaN

In [10]:
import ast
import pandas as pd

# Convert the string representation of lists into actual Python lists
df_customer["Browsing_List"] = df_customer["Browsing_History"].apply(
    ast.literal_eval
)

df_customer["Purchase_List"] = df_customer["Purchase_History"].apply(
    ast.literal_eval
)

print("Customer records:", len(df_customer))

print("\nTotal browsing interactions:",
      df_customer["Browsing_List"].apply(len).sum())

print("Total purchase interactions:",
      df_customer["Purchase_List"].apply(len).sum())

print("\nAverage browsed items per customer:",
      df_customer["Browsing_List"].apply(len).mean())

print("Average purchased items per customer:",
      df_customer["Purchase_List"].apply(len).mean())

Customer records: 10000

Total browsing interactions: 19967
Total purchase interactions: 19967

Average browsed items per customer: 1.9967
Average purchased items per customer: 1.9967

In [11]:
# Flatten purchase history
purchase_items = [
    item
    for items in df_customer["Purchase_List"]
    for item in items
]

print("Unique purchased products/items:",
      len(set(purchase_items)))

print("\nMost frequently purchased items:")
print(
    pd.Series(purchase_items)
    .value_counts()
    .head(20)
)

Unique purchased products/items: 24

Most frequently purchased items:
Moisturizer         882
Curtains            876
T-shirt             875
Smartphone          863
Headphones          856
Lipstick            855
Jeans               852
Cushions            843
Wall Art            841
Biography           836
Resistance Bands    831
Comics              829
Dumbbells           827
Treadmill           827
Yoga Mat            824
Laptop              824
Foundation          823
Smartwatch          823
Jacket              818
Non-fiction         805
Name: count, dtype: int64

In [12]:
# Flatten browsing history
browse_items = [
    item
    for items in df_customer["Browsing_List"]
    for item in items
]

print("Unique browsed items:",
      len(set(browse_items)))

print("\nMost frequently browsed items:")
print(
    pd.Series(browse_items)
    .value_counts()
    .head(20)
)

Unique browsed items: 6

Most frequently browsed items:
Electronics    3366
Beauty         3348
Home Decor     3345
Fashion        3333
Fitness        3309
Books          3266
Name: count, dtype: int64

In [13]:
purchase_counts = (
    pd.Series(purchase_items)
    .value_counts()
    .sort_values(ascending=False)
)

print(purchase_counts)

Moisturizer         882
Curtains            876
T-shirt             875
Smartphone          863
Headphones          856
Lipstick            855
Jeans               852
Cushions            843
Wall Art            841
Biography           836
Resistance Bands    831
Comics              829
Dumbbells           827
Treadmill           827
Yoga Mat            824
Laptop              824
Foundation          823
Smartwatch          823
Jacket              818
Non-fiction         805
Fiction             796
Shoes               788
Perfume             788
Lamp                785
Name: count, dtype: int64

In [14]:
print("\nNumber of customers with each purchase count:")

purchase_count_per_customer = (
    df_customer["Purchase_List"]
    .apply(len)
    .value_counts()
    .sort_index()
)

print(purchase_count_per_customer)

Number of customers with each purchase count:
Purchase_List
1    3369
2    3295
3    3336
Name: count, dtype: int64

In [15]:
print("\nCustomers with 1 purchase item:")
print((df_customer["Purchase_List"].apply(len) == 1).sum())

print("\nCustomers with 2 purchase items:")
print((df_customer["Purchase_List"].apply(len) == 2).sum())

print("\nCustomers with 3 purchase items:")
print((df_customer["Purchase_List"].apply(len) == 3).sum())

Customers with 1 purchase item:
3369

Customers with 2 purchase items:
3295

Customers with 3 purchase items:
3336

In [16]:
import pandas as pd

purchase_interactions = (
    df_customer[["Customer_ID", "Purchase_List"]]
    .explode("Purchase_List")
    .rename(columns={"Purchase_List": "Product"})
)

purchase_interactions["Purchase"] = 1

print(purchase_interactions.head())
print("\nShape:", purchase_interactions.shape)

  Customer_ID           Product  Purchase
0       C1000         Biography         1
0       C1000             Jeans         1
1       C1001         Biography         1
1       C1001  Resistance Bands         1
1       C1001           T-shirt         1

Shape: (19967, 3)

In [17]:
user_item_matrix = pd.crosstab(
    purchase_interactions["Customer_ID"],
    purchase_interactions["Product"]
)

print("Matrix shape:", user_item_matrix.shape)
display(user_item_matrix.head())

Matrix shape: (10000, 24)

Product,Biography,Comics,Curtains,Cushions,Dumbbells,Fiction,Foundation,Headphones,Jacket,Jeans,...,Non-fiction,Perfume,Resistance Bands,Shoes,Smartphone,Smartwatch,T-shirt,Treadmill,Wall Art,Yoga Mat
Customer_ID,,,,,,,,,,,,,,,,,,,,,
C1000,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
C10000,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
C10001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
C10002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C10003,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

item_similarity = cosine_similarity(user_item_matrix.T)

item_similarity_df = pd.DataFrame(
    item_similarity,
    index=user_item_matrix.columns,
    columns=user_item_matrix.columns
)

display(item_similarity_df.round(3))

Product,Biography,Comics,Curtains,Cushions,Dumbbells,Fiction,Foundation,Headphones,Jacket,Jeans,...,Non-fiction,Perfume,Resistance Bands,Shoes,Smartphone,Smartwatch,T-shirt,Treadmill,Wall Art,Yoga Mat
Product,,,,,,,,,,,,,,,,,,,,,
Biography,1.000,0.000,0.071,0.055,0.066,0.000,0.053,0.066,0.057,0.060,...,0.000,0.075,0.079,0.060,0.064,0.072,0.065,0.067,0.069,0.073
Comics,0.000,1.000,0.061,0.073,0.053,0.000,0.075,0.059,0.075,0.050,...,0.000,0.063,0.059,0.079,0.067,0.079,0.072,0.064,0.060,0.073
Curtains,0.071,0.061,1.000,0.000,0.046,0.068,0.068,0.072,0.074,0.067,...,0.058,0.072,0.063,0.078,0.078,0.077,0.077,0.060,0.000,0.068
Cushions,0.055,0.073,0.000,1.000,0.062,0.059,0.066,0.048,0.069,0.081,...,0.066,0.074,0.059,0.065,0.068,0.065,0.078,0.087,0.000,0.056
Dumbbells,0.066,0.053,0.046,0.062,1.000,0.070,0.069,0.064,0.066,0.081,...,0.071,0.069,0.000,0.052,0.072,0.065,0.076,0.000,0.077,0.000
Fiction,0.000,0.000,0.068,0.059,0.070,1.000,0.067,0.076,0.068,0.085,...,0.000,0.061,0.064,0.064,0.049,0.073,0.071,0.059,0.055,0.083
Foundation,0.053,0.075,0.068,0.066,0.069,0.067,1.000,0.066,0.069,0.063,...,0.066,0.000,0.060,0.075,0.058,0.041,0.057,0.065,0.066,0.063
Headphones,0.066,0.059,0.072,0.048,0.064,0.076,0.066,1.000,0.075,0.059,...,0.060,0.072,0.047,0.071,0.000,0.000,0.065,0.074,0.059,0.076
Jacket,0.057,0.075,0.074,0.069,0.066,0.068,0.069,0.075,1.000,0.000,...,0.060,0.062,0.057,0.000,0.073,0.063,0.000,0.073,0.059,0.063
Jeans,0.060,0.050,0.067,0.081,0.081,0.085,0.063,0.059,0.000,1.000,...,0.066,0.066,0.063,0.000,0.061,0.049,0.000,0.067,0.066,0.061
Lamp,0.077,0.068,0.000,0.000,0.065,0.063,0.072,0.072,0.045,0.064,...,0.073,0.056,0.078,0.060,0.060,0.063,0.076,0.066,0.000,0.081
Laptop,0.061,0.068,0.059,0.072,0.070,0.064,0.072,0.000,0.066,0.068,...,0.079,0.063,0.065,0.063,0.000,0.000,0.073,0.065,0.073,0.067
Lipstick,0.072,0.067,0.074,0.080,0.059,0.062,0.000,0.064,0.065,0.067,...,0.076,0.000,0.064,0.068,0.079,0.056,0.077,0.069,0.066,0.063
Moisturizer,0.066,0.058,0.068,0.068,0.076,0.075,0.000,0.058,0.062,0.066,...,0.075,0.000,0.065,0.058,0.084,0.082,0.061,0.083,0.070,0.062
Non-fiction,0.000,0.000,0.058,0.066,0.071,0.000,0.066,0.060,0.060,0.066,...,1.000,0.069,0.083,0.055,0.062,0.055,0.074,0.051,0.052,0.061
Perfume,0.075,0.063,0.072,0.074,0.069,0.061,0.000,0.072,0.062,0.066,...,0.069,1.000,0.074,0.058,0.078,0.072,0.073,0.057,0.066,0.052
Resistance Bands,0.079,0.059,0.063,0.059,0.000,0.064,0.060,0.047,0.057,0.063,...,0.083,0.074,1.000,0.078,0.060,0.063,0.061,0.000,0.061,0.000
Shoes,0.060,0.079,0.078,0.065,0.052,0.064,0.075,0.071,0.000,0.000,...,0.055,0.058,0.078,1.000,0.063,0.073,0.000,0.069,0.054,0.063
Smartphone,0.064,0.067,0.078,0.068,0.072,0.049,0.058,0.000,0.073,0.061,...,0.062,0.078,0.060,0.063,1.000,0.000,0.062,0.066,0.085,0.056
Smartwatch,0.072,0.079,0.077,0.065,0.065,0.073,0.041,0.000,0.063,0.049,...,0.055,0.072,0.063,0.073,0.000,1.000,0.071,0.063,0.071,0.072
T-shirt,0.065,0.072,0.077,0.078,0.076,0.071,0.057,0.065,0.000,0.000,...,0.074,0.073,0.061,0.000,0.062,0.071,1.000,0.069,0.064,0.075
Treadmill,0.067,0.064,0.060,0.087,0.000,0.059,0.065,0.074,0.073,0.067,...,0.051,0.057,0.000,0.069,0.066,0.063,0.069,1.000,0.073,0.000
Wall Art,0.069,0.060,0.000,0.000,0.077,0.055,0.066,0.059,0.059,0.066,...,0.052,0.066,0.061,0.054,0.085,0.071,0.064,0.073,1.000,0.073
Yoga Mat,0.073,0.073,0.068,0.056,0.000,0.083,0.063,0.076,0.063,0.061,...,0.061,0.052,0.000,0.063,0.056,0.072,0.075,0.000,0.073,1.000

In [19]:
def recommend_products(customer_id, n=5):

    purchased = user_item_matrix.loc[customer_id]

    purchased_products = purchased[purchased > 0].index.tolist()

    scores = item_similarity_df[purchased_products].sum(axis=1)

    # Remove products already purchased
    scores = scores.drop(purchased_products, errors="ignore")

    recommendations = (
        scores
        .sort_values(ascending=False)
        .head(n)
    )

    return recommendations

In [20]:
customer_id = df_customer["Customer_ID"].iloc[0]

print("Customer:", customer_id)

print("\nPurchased products:")
print(
    df_customer.loc[
        df_customer["Customer_ID"] == customer_id,
        "Purchase_List"
    ].iloc[0]
)

print("\nRecommended products:")
print(recommend_products(customer_id, 5))

Customer: C1000

Purchased products:
['Biography', 'Jeans']

Recommended products:
Product
Dumbbells           0.147156
Resistance Bands    0.142172
Perfume             0.141060
Lamp                0.140118
Lipstick            0.138935
dtype: float64

In [21]:
print("Matrix shape:", user_item_matrix.shape)

Matrix shape: (10000, 24)

In [22]:
for product in ["Laptop", "Jeans", "Smartphone", "T-shirt"]:
    print(f"\nSimilar products to {product}:")
    print(
        item_similarity_df[product]
        .sort_values(ascending=False)
        .iloc[1:6]
    )

Similar products to Laptop:
Product
Non-fiction    0.078581
Wall Art       0.073277
T-shirt        0.073017
Cushions       0.071990
Foundation     0.071645
Name: Laptop, dtype: float64

Similar products to Jeans:
Product
Fiction      0.085001
Cushions     0.081417
Dumbbells    0.081010
Laptop       0.068029
Curtains     0.067136
Name: Jeans, dtype: float64

Similar products to Smartphone:
Product
Wall Art       0.084514
Moisturizer    0.083673
Lipstick       0.079163
Curtains       0.078208
Perfume        0.077609
Name: Smartphone, dtype: float64

Similar products to T-shirt:
Product
Cushions     0.078011
Lipstick     0.077462
Curtains     0.076528
Dumbbells    0.076411
Lamp         0.076015
Name: T-shirt, dtype: float64

In [23]:
import numpy as np

def recommend_from_items(purchased_products, n=5):

    scores = item_similarity_df[purchased_products].sum(axis=1)

    # Remove products already known to the model
    scores = scores.drop(
        labels=purchased_products,
        errors="ignore"
    )

    return scores.sort_values(ascending=False).head(n).index.tolist()

In [24]:
def evaluate_recommender(k=5):

    hits = 0
    total = 0

    precision_sum = 0
    recall_sum = 0

    for _, row in df_customer.iterrows():

        purchased = row["Purchase_List"]

        # Need at least 2 products
        if len(purchased) < 2:
            continue

        # Use the first products as training
        train_items = purchased[:-1]

        # Last product is the hidden test item
        test_item = purchased[-1]

        recommendations = recommend_from_items(
            train_items,
            n=k
        )

        # Hit Rate
        if test_item in recommendations:
            hits += 1

        # Precision@K
        relevant = len(set(recommendations) & {test_item})
        precision_sum += relevant / k

        # Recall@K
        recall_sum += relevant / 1

        total += 1

    hit_rate = hits / total
    precision = precision_sum / total
    recall = recall_sum / total

    return hit_rate, precision, recall

In [25]:
hit_rate, precision, recall = evaluate_recommender(k=5)

print(f"Hit Rate@5 : {hit_rate:.4f}")
print(f"Precision@5: {precision:.4f}")
print(f"Recall@5   : {recall:.4f}")

Hit Rate@5 : 0.3360
Precision@5: 0.0672
Recall@5   : 0.3360

In [26]:
product_popularity = (
    purchase_interactions["Product"]
    .value_counts()
)

print(product_popularity)

Product
Moisturizer         882
Curtains            876
T-shirt             875
Smartphone          863
Headphones          856
Lipstick            855
Jeans               852
Cushions            843
Wall Art            841
Biography           836
Resistance Bands    831
Comics              829
Dumbbells           827
Treadmill           827
Yoga Mat            824
Laptop              824
Foundation          823
Smartwatch          823
Jacket              818
Non-fiction         805
Fiction             796
Shoes               788
Perfume             788
Lamp                785
Name: count, dtype: int64

In [27]:
def popularity_recommend(customer_id, k=5):
    purchased = set(
        user_item_matrix.loc[customer_id]
        [user_item_matrix.loc[customer_id] > 0]
        .index
    )

    recommendations = [
        product
        for product in product_popularity.index
        if product not in purchased
    ]

    return recommendations[:k]

In [28]:
def evaluate_popularity(k=5):

    hits = 0
    total_precision = 0
    total_recall = 0
    evaluated_users = 0

    for customer_id, group in purchase_interactions.groupby("Customer_ID"):

        actual_items = group["Product"].tolist()

        # Need at least 2 purchases
        if len(actual_items) < 2:
            continue

        # Use first item as training item
        train_items = actual_items[:-1]
        test_item = actual_items[-1]

        recommendations = popularity_recommend(customer_id, k)

        if test_item in recommendations:
            hits += 1

        total_precision += (
            1 / k if test_item in recommendations else 0
        )

        total_recall += (
            1 if test_item in recommendations else 0
        )

        evaluated_users += 1

    hit_rate = hits / evaluated_users
    precision = total_precision / evaluated_users
    recall = total_recall / evaluated_users

    return hit_rate, precision, recall

In [29]:
pop_hit, pop_precision, pop_recall = evaluate_popularity(k=5)

print(f"Popularity Hit Rate@5 : {pop_hit:.4f}")
print(f"Popularity Precision@5: {pop_precision:.4f}")
print(f"Popularity Recall@5   : {pop_recall:.4f}")

Popularity Hit Rate@5 : 0.0000
Popularity Precision@5: 0.0000
Popularity Recall@5   : 0.0000

In [30]:
def evaluate_popularity_correct(k=5):

    hits = 0
    total_users = 0

    for customer_id, group in purchase_interactions.groupby("Customer_ID"):

        actual_items = group["Product"].tolist()

        # Only customers with at least 2 purchases
        if len(actual_items) < 2:
            continue

        # Hold out the last purchase
        test_item = actual_items[-1]
        train_items = set(actual_items[:-1])

        # Popular products
        recommendations = [
            product
            for product in product_popularity.index
            if product not in train_items
        ][:k]

        if test_item in recommendations:
            hits += 1

        total_users += 1

    hit_rate = hits / total_users

    return hit_rate

In [31]:
pop_hit_rate = evaluate_popularity_correct(k=5)

print(f"Corrected Popularity Hit Rate@5: {pop_hit_rate:.4f}")

Corrected Popularity Hit Rate@5: 0.2330

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

def evaluate_item_cf(k=5):

    hits = 0
    total_users = 0

    for customer_id, group in purchase_interactions.groupby("Customer_ID"):

        actual_items = group["Product"].tolist()

        # Need at least 2 purchases
        if len(actual_items) < 2:
            continue

        # Hold out one purchase
        test_item = actual_items[-1]
        train_items = actual_items[:-1]

        # Calculate recommendation score from training items
        scores = pd.Series(
            0.0,
            index=item_similarity_df.index
        )

        for item in train_items:
            if item in item_similarity_df.columns:
                scores += item_similarity_df[item]

        # Remove products already seen during training
        scores = scores.drop(
            labels=train_items,
            errors="ignore"
        )

        recommendations = (
            scores
            .sort_values(ascending=False)
            .head(k)
            .index
            .tolist()
        )

        if test_item in recommendations:
            hits += 1

        total_users += 1

    hit_rate = hits / total_users

    return hit_rate

In [33]:
cf_hit_rate = evaluate_item_cf(k=5)

print(f"Corrected Item-CF Hit Rate@5: {cf_hit_rate:.4f}")

Corrected Item-CF Hit Rate@5: 0.3360

In [34]:
# Create browsing-category → purchased-product pairs

browsing_purchase_pairs = []

for _, row in df_customer.iterrows():

    browsing_categories = row["Browsing_List"]
    purchased_products = row["Purchase_List"]

    for category in browsing_categories:
        for product in purchased_products:
            browsing_purchase_pairs.append(
                (category, product)
            )

browsing_purchase_df = pd.DataFrame(
    browsing_purchase_pairs,
    columns=["Category", "Product"]
)

print("Browsing-Purchase pairs:", len(browsing_purchase_df))
display(browsing_purchase_df.head(20))

Browsing-Purchase pairs: 46573

       Category           Product
0         Books         Biography
1         Books             Jeans
2       Fashion         Biography
3       Fashion             Jeans
4         Books         Biography
5         Books  Resistance Bands
6         Books           T-shirt
7       Fitness         Biography
8       Fitness  Resistance Bands
9       Fitness           T-shirt
10      Fashion         Biography
11      Fashion  Resistance Bands
12      Fashion           T-shirt
13  Electronics        Smartphone
14   Home Decor          Wall Art
15      Fashion             Shoes
16      Fashion              Lamp
17   Home Decor             Shoes
18   Home Decor              Lamp
19   Home Decor          Curtains

In [35]:
category_product_counts = pd.crosstab(
    browsing_purchase_df["Category"],
    browsing_purchase_df["Product"]
)

print("Category-Product matrix shape:",
      category_product_counts.shape)

display(category_product_counts)

Category-Product matrix shape: (6, 24)

Product,Biography,Comics,Curtains,Cushions,Dumbbells,Fiction,Foundation,Headphones,Jacket,Jeans,...,Non-fiction,Perfume,Resistance Bands,Shoes,Smartphone,Smartwatch,T-shirt,Treadmill,Wall Art,Yoga Mat
Category,,,,,,,,,,,,,,,,,,,,,
Beauty,223,219,242,242,228,216,823,219,214,221,...,235,788,220,210,254,209,230,229,225,200
Books,836,829,219,209,214,796,214,219,213,218,...,805,215,235,208,204,229,238,199,196,238
Electronics,221,228,245,213,227,215,197,856,230,200,...,211,232,197,220,863,823,232,224,242,225
Fashion,203,229,253,246,229,235,218,227,818,852,...,210,211,215,788,219,212,875,231,204,218
Fitness,238,206,202,221,827,224,213,220,213,228,...,218,204,831,212,215,217,240,827,237,824
Home Decor,227,218,876,843,207,200,226,212,205,235,...,204,218,217,209,247,229,252,238,841,231

In [36]:
category_product_probability = (
    category_product_counts
    .div(category_product_counts.sum(axis=1), axis=0)
)

display(category_product_probability.round(4))

Product,Biography,Comics,Curtains,Cushions,Dumbbells,Fiction,Foundation,Headphones,Jacket,Jeans,...,Non-fiction,Perfume,Resistance Bands,Shoes,Smartphone,Smartwatch,T-shirt,Treadmill,Wall Art,Yoga Mat
Category,,,,,,,,,,,,,,,,,,,,,
Beauty,0.0286,0.0280,0.0310,0.0310,0.0292,0.0277,0.1054,0.0280,0.0274,0.0283,...,0.0301,0.1009,0.0282,0.0269,0.0325,0.0268,0.0294,0.0293,0.0288,0.0256
Books,0.1093,0.1084,0.0286,0.0273,0.0280,0.1041,0.0280,0.0286,0.0279,0.0285,...,0.1053,0.0281,0.0307,0.0272,0.0267,0.0300,0.0311,0.0260,0.0256,0.0311
Electronics,0.0283,0.0292,0.0314,0.0273,0.0291,0.0275,0.0252,0.1096,0.0295,0.0256,...,0.0270,0.0297,0.0252,0.0282,0.1105,0.1054,0.0297,0.0287,0.0310,0.0288
Fashion,0.0262,0.0295,0.0326,0.0317,0.0295,0.0303,0.0281,0.0292,0.1054,0.1098,...,0.0271,0.0272,0.0277,0.1015,0.0282,0.0273,0.1127,0.0298,0.0263,0.0281
Fitness,0.0308,0.0266,0.0261,0.0286,0.1070,0.0290,0.0276,0.0285,0.0276,0.0295,...,0.0282,0.0264,0.1075,0.0274,0.0278,0.0281,0.0310,0.1070,0.0307,0.1066
Home Decor,0.0290,0.0279,0.1120,0.1078,0.0265,0.0256,0.0289,0.0271,0.0262,0.0301,...,0.0261,0.0279,0.0278,0.0267,0.0316,0.0293,0.0322,0.0304,0.1076,0.0295

In [37]:
def browsing_recommend(customer_id, n=5):

    customer_row = df_customer[
        df_customer["Customer_ID"] == customer_id
    ].iloc[0]

    browsing_categories = customer_row["Browsing_List"]
    purchased_products = set(customer_row["Purchase_List"])

    scores = pd.Series(
        0.0,
        index=category_product_probability.columns
    )

    for category in browsing_categories:

        if category in category_product_probability.index:
            scores += category_product_probability.loc[category]

    # Don't recommend products already purchased
    scores = scores.drop(
        labels=list(purchased_products),
        errors="ignore"
    )

    return scores.sort_values(
        ascending=False
    ).head(n)

In [38]:
customer_id = df_customer["Customer_ID"].iloc[0]

print("Customer:", customer_id)

print("\nBrowsing history:")
print(
    df_customer.loc[
        df_customer["Customer_ID"] == customer_id,
        "Browsing_List"
    ].iloc[0]
)

print("\nPurchase history:")
print(
    df_customer.loc[
        df_customer["Customer_ID"] == customer_id,
        "Purchase_List"
    ].iloc[0]
)

print("\nBrowsing-based recommendations:")
print(
    browsing_recommend(customer_id, 5)
)

Customer: C1000

Browsing history:
['Books', 'Fashion']

Purchase history:
['Biography', 'Jeans']

Browsing-based recommendations:
Product
T-shirt        0.143871
Comics         0.137929
Fiction        0.134386
Jacket         0.133256
Non-fiction    0.132342
dtype: float64

In [39]:
def get_cf_scores(customer_id):

    purchased_products = (
        user_item_matrix.loc[customer_id]
        [user_item_matrix.loc[customer_id] > 0]
        .index
        .tolist()
    )

    scores = pd.Series(
        0.0,
        index=item_similarity_df.index
    )

    for product in purchased_products:
        scores += item_similarity_df[product]

    # Remove products already purchased
    scores = scores.drop(
        labels=purchased_products,
        errors="ignore"
    )

    return scores

In [40]:
def get_browsing_scores(customer_id):

    customer_row = df_customer[
        df_customer["Customer_ID"] == customer_id
    ].iloc[0]

    browsing_categories = customer_row["Browsing_List"]
    purchased_products = set(customer_row["Purchase_List"])

    scores = pd.Series(
        0.0,
        index=category_product_probability.columns
    )

    for category in browsing_categories:

        if category in category_product_probability.index:
            scores += category_product_probability.loc[category]

    scores = scores.drop(
        labels=list(purchased_products),
        errors="ignore"
    )

    return scores

In [41]:
def min_max_normalize(scores):

    if scores.max() == scores.min():
        return scores * 0

    return (
        (scores - scores.min())
        / (scores.max() - scores.min())
    )

In [42]:
def hybrid_recommend(
    customer_id,
    n=5,
    cf_weight=0.7,
    browsing_weight=0.3
):

    cf_scores = get_cf_scores(customer_id)
    browsing_scores = get_browsing_scores(customer_id)

    # Normalize scores
    cf_scores = min_max_normalize(cf_scores)
    browsing_scores = min_max_normalize(browsing_scores)

    # Combine scores
    hybrid_scores = (
        cf_weight * cf_scores
        +
        browsing_weight * browsing_scores
    )

    return (
        hybrid_scores
        .sort_values(ascending=False)
        .head(n)
    )

In [43]:
customer_id = "C1000"

print("Customer:", customer_id)

print("\nPurchase History:")
print(
    df_customer.loc[
        df_customer["Customer_ID"] == customer_id,
        "Purchase_List"
    ].iloc[0]
)

print("\nBrowsing History:")
print(
    df_customer.loc[
        df_customer["Customer_ID"] == customer_id,
        "Browsing_List"
    ].iloc[0]
)

print("\nHybrid Recommendations:")
print(
    hybrid_recommend(customer_id, n=5)
)

Customer: C1000

Purchase History:
['Biography', 'Jeans']

Browsing History:
['Books', 'Fashion']

Hybrid Recommendations:
Product
Dumbbells           0.718190
Resistance Bands    0.685367
Lipstick            0.668331
Curtains            0.667467
Perfume             0.667139
dtype: float64

In [44]:
hybrid_recommend("C1000", n=5)

Product
Dumbbells           0.718190
Resistance Bands    0.685367
Lipstick            0.668331
Curtains            0.667467
Perfume             0.667139
dtype: float64